#!/usr/bin/env bash
# Bash script that will display information about subdomains

audit_subdomain () 
{
	local domain="$1"
    local subdomain="$2"
	local result
	result="$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')"

	if [[ -z $result ]]
	then
		echo "No records found for $subdomain.$domain"
	else
		local record_type
		local destination
		record_type="$(echo "$result" | awk '{print $1}')"
		destination="$(echo "$result" | awk '{print $2}')"
		echo "The subdomain $subdomain is a $record_type record and points to $destination"
	fi

}

domain="$1"
subdomain="${2}"

if [[ -z "$subdomain" ]]
then
	subdomains=("www" "lb-01" "web-01" "web-02")
else
	subdomains=("$subdomain")
fi

for subd in "${subdomains[@]}"
do
	audit_subdomain "$domain" "$subd"
