#!/usr/bin/env bash
# installs nginx and configures it on a remote server
# to serve a page displayin 'Hello World'

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
