#!/usr/bin/env bash
# configure web server for error 404 and add custom header

sudo apt-get update
sudo apt-get install -y nginx
sudo touch /var/www/html/index.html
sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
sudo touch /var/www/html/404.html
sudo sh -c "echo \"Ceci n'est pas une page\" > /var/www/html/404.html"
SERVER_CONFIG="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By $HOSTNAME;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
			rewrite ^ https://www.facebook.com/sandra.udeike?mibextid=ZbWKwL permanent;
	}
	error_page 404 /404.html;
	location = /404.html{
		internal;
	}
}"
sudo sh -c "echo '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
sudo service nginx restart
