#!/usr/bin/env bash
# Installation and configuration of  HAproxy on your lb-01 server.

# Install HAproxy on a server
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
sudo echo "
# Configuration of Haproxy using round robin algirithm
frontend sandymma.tech
        bind 0:80
        mode http
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 181691-web-01 100.25.3.168:80 check
        server 181691-web-02 52.86.148.36:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
# Restart HAproxy service
service haproxy restart
