#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
my_store=0
while [ $my_store -lt 10 ]
do
        if [[ "$my_store" -eq '3' ]]; then
                echo "bad luck"
        elif [[ "$my_store" -eq '7' ]]; then
                echo "good luck"
        else
                echo "Best School"
        fi
        ((my_store++))
done
