#!/usr/bin/env bash
#This is a Bash script that loops from 1 to 10 using while

a=0
while [ $a -lt 10 ]
do 
	if [ "$a" -eq '3' ]; then
		echo "Bad luck"
	elif [ "$a" -eq '7' ]; then
		echo "Good luck"
	else 
		echo "Best School"
	fi
	((a++))
done
