#!/usr/bin/env bash
#This is a  Bash script that displays numbers from 1 to 20 using while

a=0
while [ $a -le 20 ]
do
  echo "$a"
  case $a in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( a++))
done
